title: Zemere Awoke Kebede  @  Ethiopian Defence University
description: >- 
   The home page of Zemere Awoke

nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: Service
    url: /service/
  - title: Teaching
    url: /teaching/
  - title: People
    url: /people/
  - title: Blog
    url: /blog/
